stages:
    - test

.tests:
  stage: test
  before_script:
    - apt update && apt install -y --no-install-recommends libvirt-dev
    - pip install -r requirements.txt -r test/requirements.txt
  script:
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pytest:3.6:
  extends: .tests
  image: python:3.6

pytest:3.11:
  extends: .tests
  image: python:3.11
